name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Angular app
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Set up PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Clean install node modules
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Build project
        run: pnpm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: delivery
          path: dist/netflix-clone-angular17/browser

  deploy:
    name: Deploy on GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: read
      id-token: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: delivery

      - name: Check
        run: |
          ls -al
          pwd

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: browser
